routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('prospectos', 'Personal\PersonalController@search');
// Route::get('clientes', 'Personal\PersonalController@clientes');
// Route::get('prospectos', 'Personal\PersonalController@prospectos');
Route::get('buscarcliente','Cliente\ClienteController@buscar');
Route::resource('clientes', 'Cliente\ClienteController');
Route::resource('clientes.direccion','Cliente\ClienteDireccionController');
Route::resource('clientes.contactos','Cliente\ClienteContactosController');
Route::resource('clientes.datos','Cliente\ClienteDatosGenController');
Route::resource('clientes.crm','Cliente\ClienteCRMController');
Route::resource('personals', 'Personal\PersonalController');
Route::resource('personals.datoslaborales', 'Personal\PersonalDatosLabController');
Route::resource('personals.referenciapersonales', 'Personal\PersonalRefPersonalController');
Route::resource('personals.datosbeneficiario', 'Personal\PersonalBeneficiarioController');
Route::resource('personals.producto','Personal\PersonalProductoController');
Route::resource('personals.crm','Personal\PersonalCRMController');


Route::resource('personals.products.transactions', 'Personal\PersonalProductTransactionController',['only'=>'store']);
Route::resource('personals.product','Personal\PersonalProductController', ['only'=>'index']);
// Route::resource('datoslaborales','DatosLabController');
// Route::resource('referenciapersonales','RefPersonalController');
// Route::resource('beneficiarios', 'BeneficiariosController');
// Route::resource('prodpersonal','ProdUsuarioController');
Route::get('pruebas','PruebasController@create');
Route::resource('empleados','Empleado\EmpleadoController');
Route::resource('empleados.datoslaborales','Empleado\EmpleadosDatosLabController');
Route::resource('empleados.estudios','Empleado\EmpleadosEstudiosController');
Route::resource('empleados.emergencias','Empleado\EmpleadosEmergenciasController');
Route::resource('empleados.vacaciones','Empleado\EmpleadosVacacionesController');
Route::resource('empleados.faltas','Empleado\EmpleadosFaltasAdministrativasController');
Route::resource('contratos','Precargas\TipoContratoController');
Route::resource('bajas','Precargas\TipoBajaController');

Route::get('buscarempleado','Empleado\EmpleadoController@buscar');
    
//Añadido <Iyari> 5/dic/2017//
Route::get('sucursales',function(){
	return View::make('Sucursales.index');
});
Route::get('gastos',function(){

	return View::make('Gastos.formulario');
});
Route::get('consulta',function(){

	return View::make('Empleadoconsulta.consulta');
});
Route::get('bonos',function(){

	return View::make('Empleadobonos.bonos');
});
Route::get('comision',function(){

	return View::make('Empleadobonos.comision');
});
//   11/Dic/2017
//-----------------------------------------------------


Route::resource('formacontactos','FormaContacto\FormaContactoController');

//Route::resource('clientes','Personal\PersonalController');

Route::resource('clientes.direccionfisica','Provedor\ProvedorDireccionFisicaController');
Route::resource('clientes.contacto','Personal\PersonalContactoController');
Route::resource('clientes.datosgenerales','Personal\PersonalDatosGeneralesController', ['except'=>'show']);


//-----------------------------------------------------
Route::resource('provedores','Provedor\ProvedorController');
Route::get('buscarprovedor','Provedor\ProvedorController@buscar');
Route::resource('provedores.direccionfisica','Provedor\ProvedorDireccionFisicaController');
Route::resource('provedores.datosgenerales','Provedor\ProvedorDatosGeneralesController', ['except'=>'show']);
Route::resource('provedores.contacto','Provedor\ProvedorContactoController');
Route::resource('provedores.crm','Provedor\ProvedorCRMController');
//----------------------------------------------------------
Route::resource('giros','Giro\GiroController', ['except'=>'show']);
//---------------------------------------------------------------------

Route::get('producto', 'Producto\ProductController@search');
//---------------------------------------------------------------------------
Route::resource('areas','Area\AreaController', ['except'=>'show']);
Route::resource('puestos','Puesto\PuestoController', ['except'=>'show']);
Route::resource('bancos','Banco\BancoController', ['except'=>'show']);
//--------------------------------------------------------------------
Route::resource('gastos','Gasto\GastoController', ['except'=>'show']);
// Route::resource('gastos.create','Gasto\GastoController@create');

Route::resource('sucursales','Sucursal\SucursalController');
Route::get('sucursales.create','Sucursal\SucursalController@create');
Route::get('sucursales.index','Sucursal\SucursalController@index');

Route::resource('sucursal','Empleado\EmpleadoSucursalController');
// ruta de funcion ajax para obtener las precargas
// Route::get('getareas','Area\AreaController@getAreas');
// Route::get('getcontratos','Precargas\TipoContratoController@getContratos');
// Route::get('getbajas','Precargas\TipoBajaController@getBajas');
// Route::get('getpuestos','Puesto\PuestoController@getPuestos');
// Route::get('getsucursal','Sucursal\SucursalController@getSucursal');
// Route::get('getalmacen','Almacen\AlmacenController@getAlmacen');
// Route::get('getbancos','Banco\BancoController@getBancos');
Route::get('getgiros','Giro\GiroController@getGiros');
Route::get('getformas','FormaContacto\FormaContactoController@getFormas');
//---------------------------------------------------------

resources/views/empleadodatoslab/create.blade.php
@extends('layouts.infoempleado')
@section('infoempleado')
	{{-- expr --}}
	<div>
		<ul class="nav nav-pills nav-justified">
			<li role="presentation" class=""><a href="{{ route('empleados.show',['empleado'=>$empleado]) }}"  class="ui-tabs-anchor">Generales:</a></li>

			<li role="presentation" class="active"><a href="{{ route('empleados.datoslaborales.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Laborales:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.estudios.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Estudios:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.emergencias.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Emergencias:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.vacaciones.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Vacaciones:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.faltas.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Administrativo:</a></li>
		</ul>
	</div>
	<div class="panel-default">
		<div class="panel-heading"><h5>Laborales:
		&nbsp;&nbsp;&nbsp;&nbsp; <i class="fa fa-asterisk" aria-hidden="true"></i>Campos Requeridos</h5></div>
		<div class="panel-body">
			@if ($edit == true)
				{{-- true expr --}}

		<!-- 	<form role="form" method="POST" action="{{ route('empleados.datoslaborales.update',['datoslaborale'=>$datoslab,'empleado'=>$empleado]) }}">
				<input type="hidden" name="_method" value="PUT"> -->
				<form role="form" method="POST" action="{{ route('empleados.datoslaborales.store',['empleado'=>$empleado]) }}">

				{{ csrf_field() }}
			@else
				{{-- false expr --}}
			<form role="form" method="POST" action="{{ route('empleados.datoslaborales.store',['empleado'=>$empleado]) }}">
				{{ csrf_field() }}
			@endif
				<input type="hidden" name="empleado_id" value="{{$empleado->id}}">
				<div class="col-md-12 offset-md-2 mt-3">
					<div class="form-group col-xs-3">
						<label class="control-label" for="fechacontratacion"><i class="fa fa-asterisk" aria-hidden="true"></i>Fecha de contratación:</label>
						<input class="form-control" 
						       type="date" 
						       id="fechacontratacion" 
						       name="fechacontratacion" 
						       value="{{ $datoslab->fechacontratacion }}" 
						       required
						       @if ($edit == true)
						       readonly
						       @else
						       @endif>
					</div>
					<div class="form-group col-xs-3">
						<label class="control-label" for="contrato">Tipo de contrato:</label>
						<select type="select" class="form-control" name="contrato_id" >
							<option id="contrato_id" value="">Sin Definir</option>
							@foreach ($contratos as $contrato)
								{{-- expr --}}
								<option id="{{$contrato->id}}" value="{{$contrato->id}}" @if ($datoslab->contrato_id == $contrato->id)
									{{-- expr --}}
									selected="selected" 
								@endif>{{$contrato->nombre}}</option>
							@endforeach
						</select>
					</div>



					<div class="form-group col-xs-3">
						<label class="control-label" for="area_id">
						Área:</label>
						<select type="select" 
						        class="form-control" 
						        name="area_id"
						        >
						        <option id="area_id" value="">Sin Definir</option>
 
							@foreach ($areas as $area)
								{{-- expr --}}
								<option id="{{$area->id}}" 
									    value="{{$area->id}}" 
							@if ($datoslab->area_id == $area->id)
									{{-- expr --}}
									selected="selected" 
								@endif>{{$area->nombre}}</option>
							@endforeach
						</select>
					</div>


					
					<div class="form-group col-xs-3">
						<label class="control-label" for="puesto_id">
						Puesto:</label>
						<select type="select" name="puesto_id" id="puesto_id" class="form-control" >
							<option id="puesto_id" value="">Sin Definir</option>

							@foreach ($puestos as $puesto)
								{{-- expr --}}
								<option id="{{$puesto->id}}" 
									    value="{{$puesto->id}}" 
									    
							@if ($datoslab->puesto_id == $puesto->id)
									{{-- expr --}}
									selected
								@endif>{{$puesto->nombre}}</option>
							@endforeach
						</select>
					</div>


	<div class="form-group col-xs-3">
						<label class="control-label" for="contrato">Sucursal:</label>
						<select type="select" class="form-control" name="sucursal_id" >
							<option id="sucursal_id" value="">Sin Definir</option>
							@foreach ($sucursales as $sucursal)
								{{-- expr --}}
								<option id="{{$sucursal->id}}" value="{{$sucursal->id}}" @if ($datoslab->sucursal_id == $sucursal->id)
									{{-- expr --}}
									selected="selected" 
								@endif>{{$sucursal->nombre}}</option>
							@endforeach
						</select>
					</div>

						
					<div class="form-group col-xs-3">
						<label class="control-label" for="lugartrabajo">Lugar de Trabajo:</label>
						<select type="select" name="lugartrabajo" class="form-control" id="lugartrabajo" value="{{ $datoslab->lugartrabajo }}">
							<option id="1" value="Oficinas" @if ($datoslab->lugartrabajo == "Oficinas")
								{{-- expr --}}
								selected="selected" 
							@endif>Oficinas</option>
							<option id="2" value="Campo" @if ($datoslab->lugartrabajo == "Campo")
								{{-- expr --}}
								selected="selected" 
							@endif>Campo</option>
						</select>
					</div>


				</div>
				<div class="col-md-12 offset-md-2 mt-3">
					<div class="form-group col-xs-3">
						<label class="control-label" for="salarionom"><i class="fa fa-asterisk" aria-hidden="true"></i>Salario Nóminal:</label>
						<input class="form-control" type="text" id="salarionom" name="salarionom" value="{{ $datoslab->salarionom }}" required>
					</div>
					<div class="form-group col-xs-3">
						<label class="control-label" for="salariodia">Salario Diario:</label>
						<input class="form-control" type="text" id="salariodia" name="salariodia" value="{{ $datoslab->salariodia }}">
					</div>
					<div class="form-group col-xs-3">
						<label class="control-label" for="puesto_inicio">Puesto Inicial:</label>
						<input class="form-control" type="text" id="puesto_inicio" name="puesto_inicio" value="{{ $datoslab->puesto_inicio }}">
					</div>
					<div class="form-group col-xs-3">
						<label class="control-label" for="periodopaga">Periodicidad de Pago:</label>
						<select type="select" class="form-control" name="periodopaga" id="periodopaga">
							<option id="1" value="Semanal" @if ($datoslab->periodopaga == "Semanal")
								{{-- expr --}}
								selected="selected" 
							@endif>Semanal</option>
							<option id="2" value="Quincenal" @if ($datoslab->periodopaga == "Quincenal")
								{{-- expr --}}
								selected="selected" 
							@endif>Quincenal</option>
							<option id="3" value="Mensual" @if ($datoslab->periodopaga == "Mensual")
								{{-- expr --}}
								selected="selected" 
							@endif>Mensual</option>
						</select>
					</div>
				</div>
				<div class="col-md-12 offset-md-2 mt-3">
					<div class="form-group col-xs-3">
						<label class="control-label" for="prestaciones">Prestaciones:</label>
						<select class="form-control" type="select" name="prestaciones" id="prestaciones">
							<option id="1" value="De Ley" @if ($datoslab->prestaciones == "De Ley")
								{{-- expr --}}
								selected="selected" 
							@endif>De Ley</option>
						</select>
					</div>
					<div class="form-group col-xs-3">
						<label class="control-label" for="regimen">Régimen de Contratación:</label>
						<select class="form-control" type="select" name="regimen" id="regimen" value="{{ $datoslab->regimen }}">
							<option id="1" value="Sueldos y Salarios" @if ($datoslab->regimen == "Sueldos y Salarios")
								{{-- expr --}}
								selected="selected" 
							@endif>Sueldos y Salarios</option>
							<option id="2" value="Jubilados" @if ($datoslab->regimen == "Jubilados")
								{{-- expr --}}
								selected="selected" 
							@endif>Jubilados</option>
							<option id="3" value="Pensionados" @if ($datoslab->regimen == "Pensionados")
								{{-- expr --}}
								selected="selected" 
							@endif>Pensionados</option>
						</select>
					</div>
					<div class="form-group col-xs-3">
						<label class="control-label" for="hentrada">Hora de Entrada:</label>
						<input class="form-control" type="text" id="hentrada" name="hentrada" value="{{ $datoslab->hentrada }}">
					</div>
					<div class="form-group col-xs-3">
						<label class="control-label" for="hsalida">Hora de Salida:</label>
						<input class="form-control" type="text" id="hsalida" name="hsalida" value="{{ $datoslab->hsalida }}">
					</div>
				</div>
				<div class="col-md-12 offset-md-2 mt-3">
					<div class="form-group col-xs-3">
						<label class="control-label" for="hcomida">Tiempo de Comida:</label>
						<select class="form-control" type="select" name="hcomida" id="hcomida" value="{{ $datoslab->hcomida }}">
							<option id="1" value="0 min" @if ($datoslab->hcomida == "0 min")
								{{-- expr --}}
								selected="selected" 
							@endif>0 min.</option>
							<option id="2" value="30 min" @if ($datoslab->hcomida == "30 min")
								{{-- expr --}}
								selected="selected" 
							@endif>30 min.</option>
							<option id="3" value="45 min" @if ($datoslab->hcomida == "45 min")
								{{-- expr --}}
								selected="selected" 
							@endif>45 min.</option>
							<option id="4" value="60 min" @if ($datoslab->hcomida == "60 min")
								{{-- expr --}}
								selected="selected" 
							@endif>60 min.</option>
							<option id="5" value="1 hr 15 min" @if ($datoslab->hcomida == "1 hr 15 min")
								{{-- expr --}}
								selected="selected" 
							@endif>1 hr 15 min.</option>
							<option id="6" value="1 hr 30 min" @if ($datoslab->hcomida == "1 hr 30 min")
								{{-- expr --}}
								selected="selected" 
							@endif>1 hr 30 min.</option>
							<option id="7" value="2 hrs" @if ($datoslab->hcomida == "2 hrs")
								{{-- expr --}}
								selected="selected" 
							@endif>2 hrs.</option>
							<option id="8" value="2 hrs 30 min" @if ($datoslab->hcomida == "2 hrs 30 min")
								{{-- expr --}}
								selected="selected" 
							@endif>2 hrs 30 min.</option>
							<option id="9" value="3 hrs" @if ($datoslab->hcomida == "3 hrs")
								{{-- expr --}}
								selected="selected" 
							@endif>3 hrs.</option>
						</select>
					</div>

					
					
					<div class="form-group col-xs-3">
						<label class="control-label" for="banco">Banco:</label>
						<select class="form-control" type="select" name="banco" id="banco">


							<option id="banco" value="">Sin Definir</option>
							@foreach ($bancos as $banco)
								{{-- expr --}}
								<option id="{{$banco->nombre}}" value="{{$banco->nombre}}" @if ($datoslab->banco == $banco->nombre)
									{{-- expr --}}
									selected="selected" 
								@endif>{{$banco->nombre}}</option>
							@endforeach


						</select>
					</div>
					<div class="form-group col-xs-3">
						<label class="control-label" for="cuenta">Cuenta:</label>
						<input class="form-control" type="text" id="cuenta" name="cuenta" value="{{ $datoslab->cuenta }}">
					</div>
					<div class="form-group col-xs-3">
						<label class="control-label" for="clabe">CLABE:</label>
						<input class="form-control" type="clabe" name="clabe" id="clabe" value="{{ $datoslab->clabe }}">
					</div>
				
					<!-- <div class="form-group col-xs-3">
						<label class="control-label" for="bonopuntualidad" id="lbl_inst2">Bono Puntualidad:</label>
						<input id="boton-toggle" type="checkbox" data-toggle="toggle" data-on="Sí" data-off="No" data-style="ios" name="bonopuntualidad" @if ($datoslab->bonopuntualidad == 1)
							
							checked="checked"
						@endif>
					</div> -->
				</div>
				<div class="panel">
					<div class="panel-heading">Datos de Baja:</div>
					<div class="col-md-12 offset-md-2 mt-3">
						<div class="form-group col-xs-3">
							<label class="control-label" for="fechabaja">Fecha de la baja:</label>
							<input class="form-control" type="date" id="fechabaja" name="fechabaja" value="{{ $datoslab->fechabaja }}">
						</div>
						<div class="form-group col-xs-3">
							<label class="control-label" for="tipobaja_id">Tipo de Baja:</label>
							<select class="form-control" type="select" name="tipobaja_id" id="tipobaja_id">
								<option id="0" value="">No hay baja</option>
								@foreach ($bajas as $baja)
									{{-- expr --}}
									<option id="{{$baja->id}}" value="{{$baja->id}}" @if ($datoslab->tipobaja_id == $baja->id)
										{{-- expr --}}
										selected="selected" 
									@endif>{{ $baja->nombre }}</option>
								@endforeach
							</select>
						</div>
						<div class="form-group col-xs-3">
							<label class="control-label" for="comentariobaja">Comentarios:</label>
							<textarea class="form-control" id="comentariobaja" name="comentariobaja" maxlength="500">{{$datoslab->comentariobaja}}</textarea>
						</div>
					</div>
				</div>
				<button type="submit" class="btn btn-success">
			<strong>Guardar</strong>	
			</button>
				
			</form>
		</div>
	</div>
	<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
@endsection

resources/views/empleadodatoslab/view.blade.php
@extends('layouts.infoempleado')
@section('infoempleado')
	{{-- expr --}}
	
	<div>
		<ul class="nav nav-pills nav-justified">
			<li role="presentation" class=""><a href="{{ route('empleados.show',['empleado'=>$empleado]) }}"  class="ui-tabs-anchor">Generales:</a></li>

			<li role="presentation" class="active"><a href="{{ route('empleados.datoslaborales.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Laborales:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.estudios.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Estudios:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.emergencias.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Emergencias:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.vacaciones.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Vacaciones:</a></li>

			<li role="presentation" class=""><a href="{{ route('empleados.faltas.index',['empleado'=>$empleado]) }}" class="ui-tabs-anchor">Administrativo:</a></li>
		</ul>
	</div>
	<div class="panel-default">
		<div class="panel-heading"><h5><strong>Laborales:</strong></h5></div>
		<div class="panel-body">
			<div class="col-md-12 offset-md-2 mt-3">
				<div class="form-group col-xs-3">
					<label class="control-label" for="fechacontratacion">Fecha de contratación:</label>
					<dd>{{ $actual->fechacontratacion }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="contrato">Tipo de contrato:</label>
					<dd>{{ $contrato->nombre }}</dd>
				</div>

				<div class="form-group col-xs-3">
					<label class="control-label" for="area">Área:</label>
					
					<dd>{{ $area->nombre }}</dd>
				</div>
				
				<div class="form-group col-xs-3">
					<label class="control-label" for="puesto">Puesto:</label>
					<dd>{{ $puesto->nombre }}</dd>
				</div>

			</div>
			<div class="col-md-12 offset-md-2 mt-3">
				<div class="form-group col-xs-3">
					<label class="control-label" for="salarionom">Salario Nóminal:</label>
					<dd>{{ $actual->salarionom }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="salariodia">Salario Diario:</label>
					<dd>{{ $actual->salariodia }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="puesto_inicio">Puesto Inicial:</label>
					<dd>{{ $actual->puesto_inicio }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="periodopaga">Periodicidad de Pago:</label>
					<dd>{{ $actual->periodopaga }}</dd>
				</div>
			</div>
			<div class="col-md-12 offset-md-2 mt-3">
				<div class="form-group col-xs-3">
					<label class="control-label" for="prestaciones">Prestaciones:</label>
					<dd>{{ $actual->prestaciones }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="regimen">Régimen de Contratación:</label>
					<dd>{{ $actual->regimen }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="hentrada">Hora de Entrada:</label>
					<dd>{{ $actual->hentrada }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="hsalida">Hora de Salida:</label>
					<dd>{{ $actual->hsalida }}</dd>
				</div>
			</div>
			<div class="col-md-12 offset-md-2 mt-3">
				<div class="form-group col-xs-3">
					<label class="control-label" for="hcomida">Tiempo de Comida:</label>
					<dd>{{ $actual->hcomida }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="lugartrabajo">Lugar de Trabajo:</label>
					<dd>{{ $actual->lugartrabajo }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="banco">Banco:</label>
					<dd>{{ $actual->banco }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="cuenta">Cuenta:</label>
					<dd>{{ $actual->cuenta }}</dd>
				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="clabe">CLABE:</label>
					<dd>{{ $actual->clabe }}</dd>
				</div>
			</div>
			<div class="col-md-12 offset-md-2 mt-3">
				<div class="form-group col-xs-3">
					<label class="control-label" for="sucursal">Sucursal:</label>
					@if($sucursal==null)
					<dd>NO DEFINIDO</dd>
					@else
					<dd>{{ $sucursal->nombre }}</dd>
					@endif

				</div>
				<div class="form-group col-xs-3">
					<label class="control-label" for="almacen">Almacen:</label>
					@if($almacen==null)
					<dd>NO DEFINIDO</dd>
					@else
					<dd>{{ $almacen->nombre }}</dd>
					@endif
				</div>
			</div>
			
			<a class="btn btn-info btn-md" href="{{ route('empleados.datoslaborales.edit',['empleado'=>$empleado,'datoslaborale'=>$actual]) }}">
				<strong>Editar</strong>
			</a>
		</div>
	</div>
@endsection